// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB92ZGLZewciAsWfoxY9ETxZ9VyjJ4yGWQ',
    appId: '1:734370663348:web:d23913290cbaadf2d400e1',
    messagingSenderId: '734370663348',
    projectId: 'stock-research-app-d2013',
    authDomain: 'stock-research-app-d2013.firebaseapp.com',
    storageBucket: 'stock-research-app-d2013.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU6XQ4REiO-XZ1C8gtoFncQfhlI0xmuD0',
    appId: '1:734370663348:ios:4b1507e0bb6b6759d400e1',
    messagingSenderId: '734370663348',
    projectId: 'stock-research-app-d2013',
    storageBucket: 'stock-research-app-d2013.firebasestorage.app',
    iosBundleId: 'com.example.stockResearchApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU6XQ4REiO-XZ1C8gtoFncQfhlI0xmuD0',
    appId: '1:734370663348:ios:4b1507e0bb6b6759d400e1',
    messagingSenderId: '734370663348',
    projectId: 'stock-research-app-d2013',
    storageBucket: 'stock-research-app-d2013.firebasestorage.app',
    iosBundleId: 'com.example.stockResearchApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB92ZGLZewciAsWfoxY9ETxZ9VyjJ4yGWQ',
    appId: '1:734370663348:web:8c0cdbba4b6187ded400e1',
    messagingSenderId: '734370663348',
    projectId: 'stock-research-app-d2013',
    authDomain: 'stock-research-app-d2013.firebaseapp.com',
    storageBucket: 'stock-research-app-d2013.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFEgEdWTZIhexzUPq3ALtpWHU-BoraesQ',
    appId: '1:734370663348:android:ddaf364e8541ca7ed400e1',
    messagingSenderId: '734370663348',
    projectId: 'stock-research-app-d2013',
    storageBucket: 'stock-research-app-d2013.firebasestorage.app',
  );
}
